--- # Gathering Facts

- hosts: local
  user: vagrant
  become: yes
  gather_facts: no
  vars_files:
  - files/awscreds.yml
  tasks:
    - name: gathering remote facts
      ec2_instance_facts:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key:  "{{ aws_key }}" 
        region: "{{aws_region}}"
        filters:
          "tag:dk=docker"
      register: ec2_metadata
    - debug:
        msg: "{{ ec2_metadata.instances[0].public_ip_address }}" 
