--- # Gathering Facts

- hosts: local
  user: vagrant
  become: yes
  gather_facts: no
  vars:
    aws_domain_name: "{{ ec2_metadata.instances[0].public_dns_name }}"
  vars_files:
  - files/awscreds.yml
  tasks:
    - pause: seconds=30
    - name: gathering remote facts
      ec2_instance_facts:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key:  "{{ aws_key }}" 
        region: "{{aws_region}}"
        filters:
          "tag:dk=docker"
      register: ec2_metadata

    - debug:
        msg: "{{ aws_domain_name }}" 

    - name: remove old dns name
      lineinfile:
        path: /home/vagrant/virtualpy/aws-openshift/hosts 
        regexp: '^.*?\.compute.amazonaws\..*$'
        state: absent

    - name: add new dns name
      lineinfile:
        path: /home/vagrant/virtualpy/aws-openshift/hosts
    #    regexp: '^\[aws\]'
        insertafter: '^\[aws\]'
        line: "{{ aws_domain_name }}"
