--- # Docker Install

- hosts: aws 
  remote_user: "{{ docker_user }}"
  become: yes
  vars_files:
  - files/awscreds.yml 
  tasks:

  - name: remove centos default docker installation
    yum: pkg={{ item }} state=removed
    with_items:
      - docker
      - docker-common
      - docker-engine
      - docker-engine-selinux

  - name: install additional repos
    yum: pkg={{ item }} state=present
    with_items:
      - epel-release

  - name: install docker
    yum: pkg=docker state=present update_cache=yes

  - name: create docker group
    group:
      name: docker 
      state: present

  - name: add docker user to docker group
    user:
      name: "{{ docker_user }}"
      groups: docker

  - name: start/enable docker
    service:
      name: docker
      state: started
      enabled: yes
