# Spawn AWS EC2 and install Openshift
---
- hosts: localhost
  connection: local
  remote_user: vagrant
  become: yes
  gather_facts: false
  vars_files:
  - files/awscreds.yml
  tasks:
  - name: provision ec2 instance
    ec2: 
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}" 
      image: ami-0cfcdb69
      instance_type: t2.micro 
      region: "{{ aws_region }}"
      key_name: aws_ec2_key
      group: ansible-sg
      volumes:
        - device_name: /dev/sda1
          volume_size: 10
          delete_on_termination: true
      instance_tags:
        dk: docker
      count: 1
    register: ec2

  - name: wait for ssh to come up
    wait_for:
      host: "{{ ec2.instances[0].public_dns_name }}" 
      delay: 30
      port: 22
      timeout: 60
      state: started

  - name: remove old host entry
    lineinfile:
      path: /home/vagrant/virtualpy/aws/hosts
      state: absent
      regexp: '^.*?\.compute.amazonaws\..*$' 

  - name: add new instance public ip
    lineinfile:
      path: /home/vagrant/virtualpy/aws/hosts
      insertafter: '^\[aws\]'
      line: "{{ ec2.instances[0].public_dns_name }}" 

  - meta: refresh_inventory
