--- # Docker Install

- hosts: aws
  remote_user: "{{ aws_user }}"
  become: yes
  vars_files:
  - files/awscreds.yml 
  tasks:

  - name: remove centos default docker installation
    yum: pkg={{ item }} state=removed
    with_items:
      - docker
      - docker-common
      - docker-engine
      - docker-engine-selinux

  - name: add docker repo
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/ 
      mode: 0644

  #- name: update cache
  #  yum: pkg=* state=latest

  - name: install addtional packages
    yum: pkg={{ item }} state=present update_cache=yes
    with_items:
      - epel-release
      - yum-utils
      - device-mapper-persistent-data 
      - lvm2

  - name: install docker-ce
    yum: pkg=docker-ce state=present update_cache=yes

  - name: create docker group
    group:
      name: docker 
      state: present

  - name: add docker user to docker group
    user:
      name: "{{ aws_user }}"
      append: yes
      groups: docker

  - name: start/enable docker
    service:
      name: docker
      state: started
      enabled: yes
